image: docker:latest

variables:
        REPOSITORY_URL: laruno/laruno-api
        #TAG: latest
    
services:
    - docker:dind
    
before_script:
        #- docker image prune -f
    - docker login -u "$DOCKER_USER" --password-stdin "$DOCKER_PASS"

stages:
    - build
    - deploy

build:
    stage: build
    tags:
        - build
    script:
        - echo "Building image.."
        - docker build -t laruno-api:latest --no-cache .
        - echo "Tagging image.."
        - docker tag laruno-api:latest $REPOSITORY_URL:latest
        - echo "Pushing image.."
        - docker push $REPOSITORY_URL:latest
        
    only:
        - master

deploy:
    stage: deploy
    tags:
        - deploy
    script:
        - docker stop laruno-api || true && docker rm laruno-api || true
        - docker container run -dt -p 5000:5000 --name laruno-api $REPOSITORY_URL:latest
        - docker image prune -f
    only:
        - master
