stages:
  - publish
  - deploy
  
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  
publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
    
deploy:
  image: node:latest
  stage: deploy
  tags:
    - deployment
  script:
    #- chmod og= $SERVER_SECRET_KEY
    - apk update && apk add openssh-client
    - ssh -i $SERVER_SECRET_KEY -o "StrictHostKeyChecking=no" $SERVER_USER@$SERVER_HOST "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $SERVER_SECRET_KEY -o "StrictHostKeyChecking=no" $SERVER_USER@$SERVER_HOST "docker pull $TAG_COMMIT"
    - ssh -i $SERVER_SECRET_KEY -o "StrictHostKeyChecking=no" $SERVER_USER@$SERVER_HOST "docker container rm -f API-Client || true"
    - ssh -i $SERVER_SECRET_KEY -o "StrictHostKeyChecking=no" $SERVER_USER@$SERVER_HOST "docker run -d -p 80:80 --name API-Client $TAG_COMMIT"
    
  environment:
    name: production
    url: http://139.162.59.84
  only:
    - master
