image: node:latest

stages:
  - publish
  - deploy
  
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  
publish:
  stage: publish
  environment:
    name: development
  script:
    - npm install
    - npm run build
    
deploy:
  environment:
    name: production
    url: http://139.162.59.84
  only:
  stage: deploy
    - master
  tags:
    - deployment
  script:
    - docker install
    - docker build . -t client-api
    - docker run -d -p 5000:5000 client-api
