image: docker:latest

services: 
    - docker:dind

variables:
        REGISTRY: https://hub.docker.com/laruno/laruno-api:latest

stages:
    - deploy

docker-build:
    stage: deploy
    before_script:
        - echo $DOCKER_IMAGE
          #- echo $CI_BUILD_TOKEN | docker login -u "$DOCKER_USER" --password "$DOCKER_PASS"
    script:
        #- docker-compose -f docker-compose.yml build --no-cache
        #- docker-compose -f docker-compose.yml up -d
        #- docker image prune -f
        - docker pull laruno/laruno-api:latest
        - docker build -t laruno/laruno-api:latest --no-cache .
        - docker push laruno/laruno-api:latest
        - docker run --name=laruno-api -p 5000:5000 -i laruno/laruno-api:latest npm run ci
        #- docker stop laruno-api || true && docker rm laruno-api || true
        #- docker image prune -f
    only:
        - master
