image: laruno/laruno-api:latest

services:
    - docker:dind

stages:
    - build
    - deploy

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
    stage: build
    tags:
        - building
    script:
        - echo "Building image.."
        - docker build -t laruno/laruno-api:latest --no-cache .
        - echo "Tagging image.."
        - docker tag laruno/laruno-api:latest laruno/laruno-api:latest
        - echo "Push docker image"
        - docker push laruno/laruno-api:latest
    only:
        - master

deploy:
    stage: deploy
    tags:
        - deploying
    script:
        #- docker stop laruno/laruno-api || true && docker rm laruno/laruno-api || true
        #- docker rm -f $(docker ps -aq)
        #- docker stop $(docker ps | grep ":5000" | awk '{print $1}')
        - docker pull laruno/laruno-api:latest
          #- docker run -dt -p 5000:5000 laruno/laruno-api:latest
        - docker-compose down
        - docker-compose up -d
        - docker image prune -f
        - docker container prune -f
    only:
        - master
