stages:
  - publish
  - deploy
  
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
    
deploy:
  image: laruno/client-api
  stage: deploy
  tags:
    - deployment
  before_script: 
    - docker login -u "$DOCKER_USER" -p "$DOCKER_SECRET"
  script:
    - docker-compose up -d --build client-api -t $TAG_COMMIT -t $TAG_LATEST .
    
  environment:
    name: production
    url: http://139.162.59.84
  only:
    - master
