#image: docker:latest
image: laruno/laruno-api:latest

services:
    - docker:dind

stages:
    - build
    - deploy

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

#build:
    #tags: 
        # - building
    #script:
        # - docker build -t laruno/laruno-api --no-cache .
        # - docker run -d -p 5000:5000 laruno/laruno-api
        # - docker image prune -f
        # - docker container prune -f
    #only:
        # - master
build:
    stage: build
    tags:
        - building
    script:
        - echo "Building image.."
        - docker build -t laruno/laruno-api:latest --no-cache .
        - echo "Tagging image.."
        - docker tag laruno/laruno-api:latest laruno/laruno-api:latest
    only:
        - master

deploy:
    #image: laruno/laruno-api
    stage: deploy
    tags:
        - deployment
    script:
        #- docker build -t laruno/laruno-api .
        #- docker run laruno/laruno-api
        #- docker run -d -p 5000:5000 laruno/laruno-api -f
        # - docker image prune -f
        # - docker container prune -f
        - docker stop laruno/laruno-api || true && docker rm laruno/laruno-api || true
        - docker container run -dt -p 5000:5000 --name laruno/laruno-api:latest
        - docker image prune -f
        - docker container prune -f
    only:
        - master
