image: docker:latest

services:
    - docker:dind

stages:
    - deploy

deploy:
    image: laruno/laruno-api
    stage: deploy
    tags:
        - deployment
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
          #- docker login -u laruno -p "$DOCKER_PASS" docker.io/
    script:
        - docker build -t laruno/laruno-api --no-cache .
        - "docker run -it -p 5000:5000 laruno/laruno-api"
        - docker image prune -f
        - docker container prune -f
          #- docker run -d -p 5000:5000 laruno/laruno-api
          # - docker push laruno/laruno-api
            #- sudo apt-get install docker-compose
            #- sudo docker image prune -f
            #- sudo docker-compose -f docker-compose.yml build --no-cache
            #- sudo docker-compose -f docker-compose.yml up -d

          #- docker run -d -p 5000:5000 laruno/laruno-api
    only:
        - master
