stages:
  - deploy
    
deploy:
  image: laruno/client-api
  stage: deploy
  tags:
    - deployment
  script:
    docker-compose up -d --build client-api
    
  environment:
    name: production
    url: http://139.162.59.84
  only:
    - master
