image: docker:latest

services: 
    - docker:dind

variables:
      DOCKER_IMAGE: laruno/laruno-api

stages:
    - deploy

docker-build:
    stage: deploy
    before_script:
        - echo "$DOCKER_IMAGE"
          #- echo $CI_BUILD_TOKEN | docker login -u "$DOCKER_USER" --password "$DOCKER_PASS"
        - sudo docker login --username "$DOCKER_USER" --password-stdin "$DOCKER_PASS"
    script:
        #- docker-compose -f docker-compose.yml build --no-cache
        #- docker-compose -f docker-compose.yml up -d
        #- docker image prune -f
        - docker pull $DOCKER_IMAGE:latest 
        - docker build -t $DOCKER_IMAGE:latest --no-cache .
        - docker push $DOCKER_IMAGE
        - docker run --name=laruno-api -p 5000:5000 -i $DOCKER_IMAGE npm run ci
        - docker stop laruno-api || true && docker rm laruno-api || true
        - docker container run -dt -p 5000:5000 --name laruno-api $DOCKER_IMAGE:latest
        - docker image prune -f
    only:
        - master
