image: docker:latest
services: 
    - docker:dind

stages:
    - build

docker-build:
    stage: build
    services:
        - docker:dind
          #before_script:
          #- echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
        #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
            - sudo docker image prune -f
            - sudo docker-compose -f docker-compose.yml build --no-cache
            - sudo docker-compose -f docker-compose.yml up -d
            # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
            # - docker push "$CI_REGISTRY_IMAGE"
            #only:
            # - master
