stages:
    - deploy

deploy:
    image: docker:latest
    stage: deploy
    services:
          - docker:dind
    before_script:
          - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" -password-stdin $CI_REGISTRY
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
          #- docker run -d -p 5000:5000 laruno/laruno-api
    only:
        - master
