version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "laruno/client-api-dev:latest"
    container_name: client-api-dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    command: npm run start:prod