version: "3.8"

services:
        node:
                build: .
                dockerfile: Dockerfile
                image: "laruno/laruno-api:latest"
                container_name: laruno
                ports:
                        - "5000:5000"

        nginx:
                restart: always
                build: ./docker/nginx
                ports:
                        - "80:80"
