version: "3.7"

services:
  client-api:
    build:
      # context: ./laruno-api
      dockerfile: Dockerfile
      target: dev
    image: "laruno/client-api:latest"
    container_name: client-api
    restart: unless-stopped
    volumes:
      - ./app/laruno-api
      # - ./laruno-api/app/laruno-api
      #- ./laruno-api/app/dist
      #- ./laruno-api/app/node_modules
      #- ./laruno-api:/laruno-api/app
    command: npm run start:dev
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - CLIENT_API_PORT=${CLIENT_API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_AUTH=${DB_AUTH}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ENCRYPT_SECRETKEY=${JWT_ENCRYPT_SECRETKEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - XENDIT_API_KEY=${XENDIT_API_KEY}
      - RAJAONGKIR_API_KEY=${RAJAONGKIR_API_KEY}
    ports:
      - "5000:5000"
    # networks:
    #   - default

# networks:
#   default:
#     external:
#       name: gateway