version: "3.7"

services:
  db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment: 
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ./docker-entrypoint-mongo-inituser/init-user.js:/docker-entrypoint-mongo-inituser/init-user.js:ro
    networks:
      - default
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      # dockerfile: Dockerfile
      target: development
    image: "laruno/client-api:latest"
    container_name: client-api
    restart: unless-stopped
    env_file: .env
    networks:
      - default
    ports:
      - "5000:5000"
    depends_on:
      - db
    
networks:
  default:
    external:
      name: gateway

    