version: "3.8"

services:
        api.laruno.id:
                build: .
                image: "laruno/laruno-api:latest"
                container_name: laruno
                volumes:
                        - /dir/on/host:/var/www/api.laruno.id
                ports:
                        - "5000:5000"
                networks:
                        - default

                          #nginx:
                          #restart: always
                          #build: ./docker/nginx
                          #ports:
                          #- "80:80"
                          #networks:
                          #- default
