version: "3.8"
services:
    nodeserver:
        build:
            #context: ./docker/node
            context: ./app/laruno-api/docker/node
            #dockerfile: ./app/laruno-api/docker/Dockerfile
            #image: "laruno/laruno-api:latest"
            #container_name: client-api
            #restart: unless-stopped
        ports:
            - "5000:5000"
            
    nginx:
        restart: always
        build:
            context: ./docker/nginx
        ports:
            - "80:80"
