version: "3.8"

services:
        nodeserver:
                build: .
                image: "laruno/laruno-api:latest"
                container_name: laruno
                ports:
                        - "5000:5000"
                networks:
                        - default

        nginx:
                restart: always
                build: ./docker/nginx
                ports:
                        - "80:80"
                networks:
                        - default
