version: "3.8"

services:
        nodeserver:
                build: ./docker/node
                ports:
                        - "5000:5000"

        nginx:
                restart: always
                build: ./docker/nginx
                ports:
                        - "80:80"
