import { IProduct } from '../product/interfaces/product.interface';

export const prepareProduct = (product: any): IProduct => ({
    _id: product._id,
    code: product.code,
    type: product.type,
    name: product.name,
    slug: product.slug,
    visibility: product.visibility,
    topic: product.topic,
    image_url: product.image_url,
    video_url: product.video_url,
    headline: product.headline,
    description: product.description,
    feedback: product.feedback,
    time_period: product.time_period,
    price: product.price,
    created_by: product.created_by,
    updated_by: product.updated_by,
    webinar: product.webinar,
    sale_method: product.sale_method,
    product_redirect: product.product_redirect,
    reseller: product.reseller,
    image_bonus_url: product.image_bonus_url,
    image_text_url: product.image_text_url,
    image_product_url: product.image_product_url,
    section: product.section,
    created_at: product.created_at,
    updated_at: product.updated_at
});